spring:
  datasource:
    url: jdbc:h2:mem:upload;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create-drop     # 테스트 끝나면 자동 삭제되게
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 100
    open-in-view: false

  thymeleaf:
    cache: false

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace

file:
  upload:
    path: C:\workspace\test_upload_folder    # 테스트 전용 업로드 경로

# 아래는 테스트에 불필요하므로 생략하거나 비워둠
# devtools 설정 등은 테스트에 영향 없음
